# 3.Index
데이터에 접근할 수 있는 주소 값

In [52]:
import pandas as pd
data={
    '日本語' : ['リンゴ','オレンジ','パイナップル','イチゴ','ナシ'],
    'English' : ['apple','orange','pineapple','strawberry','pear'],
    '한글' : ['사과','오랜지','파인애플','딸기','배']
}

df = pd.DataFrame(data,index=['no1','no2','no3','no4','no5'])
df

        日本語     English    한글
no1     リンゴ       apple    사과
no2    オレンジ      orange   오랜지
no3  パイナップル   pineapple  파인애플
no4     イチゴ  strawberry    딸기
no5      ナシ        pear     배

In [53]:
df.index

Index(['no1', 'no2', 'no3', 'no4', 'no5'], dtype='object')

## Index 이름설정

In [54]:
df.index.name='서열'
df

        日本語     English    한글
서열
no1     リンゴ       apple    사과
no2    オレンジ      orange   오랜지
no3  パイナップル   pineapple  파인애플
no4     イチゴ  strawberry    딸기
no5      ナシ        pear     배

## Index 초기화

In [55]:
df.reset_index()

    서열     日本語     English    한글
0  no1     リンゴ       apple    사과
1  no2    オレンジ      orange   오랜지
2  no3  パイナップル   pineapple  파인애플
3  no4     イチゴ  strawberry    딸기
4  no5      ナシ        pear     배

In [56]:
df.reset_index(drop=True) # 원래쓰던 index 삭제

      日本語     English    한글
0     リンゴ       apple    사과
1    オレンジ      orange   오랜지
2  パイナップル   pineapple  파인애플
3     イチゴ  strawberry    딸기
4      ナシ        pear     배

In [57]:
df

        日本語     English    한글
서열
no1     リンゴ       apple    사과
no2    オレンジ      orange   오랜지
no3  パイナップル   pineapple  파인애플
no4     イチゴ  strawberry    딸기
no5      ナシ        pear     배

In [58]:
df.reset_index(drop=True,inplace=True)  #실제 데이터에 바로반영
df

      日本語     English    한글
0     リンゴ       apple    사과
1    オレンジ      orange   오랜지
2  パイナップル   pineapple  파인애플
3     イチゴ  strawberry    딸기
4      ナシ        pear     배

## Index 설정
지정한 column으로 index 를 설정

In [59]:
df.set_index('日本語')

           English    한글
日本語
リンゴ          apple    사과
オレンジ        orange   오랜지
パイナップル   pineapple  파인애플
イチゴ     strawberry    딸기
ナシ            pear     배

In [60]:
df

      日本語     English    한글
0     リンゴ       apple    사과
1    オレンジ      orange   오랜지
2  パイナップル   pineapple  파인애플
3     イチゴ  strawberry    딸기
4      ナシ        pear     배

In [61]:
df.set_index("한글",inplace=True)
df

         日本語     English
한글
사과       リンゴ       apple
오랜지     オレンジ      orange
파인애플  パイナップル   pineapple
딸기       イチゴ  strawberry
배         ナシ        pear

## Index 정렬
Index 를 기준으로 오름차순, 내림차순 정렬

In [62]:
df.sort_index() #Index 오름차순 정렬

         日本語     English
한글
딸기       イチゴ  strawberry
배         ナシ        pear
사과       リンゴ       apple
오랜지     オレンジ      orange
파인애플  パイナップル   pineapple

In [63]:
df.sort_index(ascending=False) #Index 내림차순 정렬

         日本語     English
한글
파인애플  パイナップル   pineapple
오랜지     オレンジ      orange
사과       リンゴ       apple
배         ナシ        pear
딸기       イチゴ  strawberry